#!/bin/bash
# Source this to talk to a Booster robot from this workstation over one
# network interface (typically the USB Ethernet adapter plugged into the
# robot), the way crl-humanoid-ros drives a G1 from the laptop:
#
#   source scripts/robot_link.sh <adapter interface or its IPv4> [ROS domain]
#
# It sources ROS 2 Humble, the booster_interface workspace and .venv, sets
# ROS_DOMAIN_ID (default 0, the robot's default) and pins Fast DDS to the
# given interface with a generated profile, so discovery and traffic never
# wander onto WiFi, Tailscale or a Docker bridge.  Afterwards:
#
#   booster_link_check                                   # sees /low_state?
#   python scripts/deploy.py --task <name> --monitor     # crl way: everything here
#   python scripts/monitor.py --robot k1                 # README way: deploy runs on the robot
#
# Override the workspace with BOOSTER_ROS2_WS.

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    echo "source this script, do not execute it:" >&2
    echo "  source $0 <adapter interface or IPv4> [ROS domain]" >&2
    exit 2
fi

_link_repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
_link_target="$1"
_link_domain="${2:-0}"
if [ -z "$_link_target" ]; then
    echo "usage: source scripts/robot_link.sh <adapter interface or IPv4> [ROS domain]" >&2
    return 2
fi

# interface name -> IPv4
if [[ "$_link_target" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    _link_ip="$_link_target"
else
    _link_ip="$(ip -4 -o addr show dev "$_link_target" 2>/dev/null \
        | awk '{print $4}' | cut -d/ -f1 | head -1)"
    if [ -z "$_link_ip" ]; then
        echo "no IPv4 address on interface '$_link_target'; plug the adapter in" >&2
        echo "and give it an address on the robot's subnet first" >&2
        return 1
    fi
fi

# ROS 2 + booster_interface + venv
source /opt/ros/humble/setup.bash
_link_ws="${BOOSTER_ROS2_WS:-$HOME/stmr/booster_ros2_ws}"
if [ -f "$_link_ws/install/setup.bash" ]; then
    source "$_link_ws/install/setup.bash"
else
    echo "warning: booster_interface workspace not found at $_link_ws" >&2
fi
[ -f "$_link_repo/.venv/bin/activate" ] && source "$_link_repo/.venv/bin/activate"

# Fast DDS: one UDPv4 transport on the adapter only, no other interfaces
mkdir -p "$_link_repo/logs"
export FASTRTPS_DEFAULT_PROFILES_FILE="$_link_repo/logs/fastdds_link.xml"
cat > "$FASTRTPS_DEFAULT_PROFILES_FILE" <<XML
<?xml version="1.0" encoding="UTF-8" ?>
<!-- generated by scripts/robot_link.sh: pin Fast DDS to $_link_ip -->
<profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
    <transport_descriptors>
        <transport_descriptor>
            <transport_id>link_udp</transport_id>
            <type>UDPv4</type>
            <interfaceWhiteList>
                <address>$_link_ip</address>
            </interfaceWhiteList>
        </transport_descriptor>
    </transport_descriptors>
    <participant profile_name="link_participant" is_default_profile="true">
        <rtps>
            <userTransports>
                <transport_id>link_udp</transport_id>
            </userTransports>
            <useBuiltinTransports>false</useBuiltinTransports>
        </rtps>
    </participant>
</profiles>
XML
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
export ROS_DOMAIN_ID="$_link_domain"
unset ROS_LOCALHOST_ONLY

booster_link_check() {
    # Is the robot's ROS 2 bridge visible over the link?
    echo "domain $ROS_DOMAIN_ID, interface $_link_ip; listening 5 s for /low_state ..."
    local hz
    hz="$(timeout 6 ros2 topic hz /low_state --window 200 2>/dev/null | grep -m1 "average rate")"
    if [ -n "$hz" ]; then
        echo "  /low_state: $hz"
    else
        echo "  /low_state: nothing received. Check the cable, the adapter's"
        echo "  address on the robot's subnet and the robot's ROS_DOMAIN_ID."
        return 1
    fi
    if ros2 service list 2>/dev/null | grep -q booster_rpc_service; then
        echo "  booster_rpc_service: available"
    else
        echo "  booster_rpc_service: not found (mode switches will fail)"
        return 1
    fi
    echo "link ok"
}

echo "robot link: interface $_link_ip, ROS_DOMAIN_ID=$ROS_DOMAIN_ID, Fast DDS profile $FASTRTPS_DEFAULT_PROFILES_FILE"
echo "next: booster_link_check, then 'python scripts/deploy.py --task <name> --monitor'"
